version: "3.8"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        depends_on: 
            - database
        environment: 
            - REDIS_IP=redis
            - REDIS_PORT=6379
            - DB_HOST=database
            - DB_PORT=3306
        env_file: .env

    worker:
        build: 
            context: .
            dockerfile: Dockerfile.worker
        environment: 
            - REDIS_IP=redis
            - REDIS_PORT=6379
            - DB_HOST=database
            - DB_PORT=3306
        env_file: .env
        depends_on: 
            - redis 
            - database

    redis:
        image: "redis:alpine"
        container_name: redis
        expose:
            - 6379

    database:
        container_name: database
        image: "mysql:latest"
        env_file: .env
        ports: 
            - "33061:3306"